preload = ~/Pictures/wallpapers/purple-forest.jpeg
wallpaper = eDP-1, ~/Pictures/wallpapers/purple-forest.jpeg
wallpaper = DP-1, ~/Pictures/wallpapers/purple-forest.jpeg
wallpaper = DP-2, ~/Pictures/wallpapers/purple-forest.jpeg
wallpaper = DP-3, ~/Pictures/wallpapers/purple-forest.jpeg
wallpaper = HDMI-A-1, ~/Pictures/wallpapers/purple-forest.jpeg
